### ISSUE TITLE
cleanup of temp directory is required

### ISSUE THREAD

**Issue by benoitdechateauvieux** [jcabi/jcabi-maven-plugin#40] opened 2015-10-30 03:05 UTC
Hi,

I use the following settings:
```xml
<plugin>
          <groupId>com.jcabi</groupId>
          <artifactId>jcabi-maven-plugin</artifactId>
          <version>${version.jcabi.plugin}</version>
          <executions>
            <execution>
              <id>weave-classes</id>
              <phase>process-classes</phase>
              <goals>
                <goal>ajc</goal>
              </goals>
              <configuration>
                <classesDirectory>${project.build.outputDirectory}</classesDirectory>
              </configuration>
            </execution>
            <execution>
              <id>weave-test-classes</id>
              <phase>process-test-classes</phase>
              <goals>
                <goal>ajc</goal>
              </goals>
              <configuration>
                <classesDirectory>${project.build.testOutputDirectory}</classesDirectory>
              </configuration>
            </execution>
          </executions>
        </plugin>
```

The result is:
- all the classes declared in src/main/java are compiled in target/classes
- all the classes declared in src/test/java **and src/main/java** are compiled in target/test-classes

This doesn't match the Maven convention (src/main/xxx => target/classes, src/test/xxx => target/test-classes)

This jar hell is detected by Elasticsearch BootstrapForTesting tool and thus Elasticsearch refuses to start.

Am I wrong in the way I setup the plugin ?
I there any way to fix that?
Thanks !

**Comment by dmarkov** [comment] 2015-11-02 07:03
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://www.teamed.io/policy.html#21)

**Comment by yegor256** [comment] 2015-11-02 18:09
@benoitdechateauvieux check this, maybe it will help: https://github.com/jcabi/jcabi-parent/blob/0.37.1/pom.xml#L467-L510 I suspect, the problem is with the temp directory

**Comment by benoitdechateauvieux** [comment] 2015-11-03 02:28
@yegor256 Yes! This solved my problem.
It could be a good idea to clean up the default temp directory after every execution to avoid this kind of unexpected behavior.

**Comment by yegor256** [comment] 2015-11-03 03:28
@benoitdechateauvieux indeed, it's a good idea, we'll implement it, thanks

**Comment by dmarkov** [comment] 2016-01-19 09:57
@piddubnyi please help, the task is yours

**Comment by piddubnyi** [comment] 2016-01-26 08:25
@benoitdechateauvieux The fix is merged. Please close the issue.

**Closed** 2016-01-26 08:41 UTC
Labels: 30 mins, @piddubnyi, bug, DEV

**Comment by dmarkov** [comment] 2016-01-27 13:20
@piddubnyi I added **30 mins** to your account, many thanks for working with the project (75790980)! The completion time here was 171 hours and 1 min.

+30 to your rating, your total score is [+120](http://www.netbout.com/b/35966?open=rating)
